// Generated by CoffeeScript 1.12.1
(function() {
  var express, testApp;

  express = require('express');

  testApp = express();

  module.exports = function(p) {
    testApp.use('/', function(req, res) {
      console.log('headers', req.headers);
      console.log('path was', req.path);
      return res.status(200).append("X-DS-service", "test/app on port " + p).send("<html> <head> <title>test</title> </head><body> <b>Req-headers:</b> <pre>" + (JSON.stringify(req.headers, null, " ")) + "</pre></body></html>");
    });
    testApp.listen(p);
    return console.log("test data on :" + p);
  };

}).call(this);

//# sourceMappingURL=test-app.js.map
