// Generated by CoffeeScript 1.12.1
(function() {
  var router;

  router = (require('express')).Router();

  module.exports = function(passport, conf, callbackPath) {
    router.get('/login', function(req, res) {
      return res.send("<html><title>login-page</title><head> <script src=\"https://cdn.auth0.com/js/lock/10.6/lock.min.js\">// </script> </head><body> <script> (new Auth0Lock('" + conf.clientID + "', '" + conf.domain + "', { auth: { redirectUrl: '" + conf.callbackURL + "' , responseType: 'code' , params: { scope: 'openid name email picture' }}})).show(); </script> </body><html>");
    });
    router.get('/logout', function(req, res) {
      req.logout();
      return res.redirect('/');
    });
    return router.get(callbackPath, passport.authenticate('auth0', {
      failureRedirect: '/url-if-something-fails'
    }), function(req, res) {
      return res.redirect(req.session.returnTo || '/?no-returnTo-data&');
    });
  };

}).call(this);

//# sourceMappingURL=security.js.map
