// Generated by CoffeeScript 1.12.1
(function() {
  var httpProxy, proxy, router;

  router = (require('express')).Router();

  httpProxy = require('http-proxy');

  proxy = httpProxy.createServer({});

  module.exports = function(port) {
    router.use('/', function(req, res) {
      return proxy.web(req, res, {
        target: "http://localhost:" + port
      });
    });
    return router;
  };

}).call(this);

//# sourceMappingURL=test.js.map
